// Auto-generated listeners registry - DO NOT EDIT MANUALLY
// This file is generated by the Vite listeners plugin



const listeners: Map<string, (payload: any) => void> = new Map();



export { listeners };
